### ISSUE TITLE
urlocator: text "Makefile:177" is detected as url "file:177"

### ISSUE THREAD

**Issue by Astranox** [alacritty/urlocator#4]
Expected behaviour: only detect as url, if scheme matches exactly
Actual behaviour: url is also detected, if there is alphanumerical text before an acceptable scheme

I think that the issue is in alacritty/urlocator, but as there are no bugs or PRs, I'm assuming that this is the proper place to report this.

System: alacritty 0.4.1 on Linux (Fedora) with X11/i3

**Comment by kchibisov** [comment]
I'm not sure that we should fix this tbh, since in terminal you can actually want wordURL patterns to work. For example imagine if I have a split in tmux and URL is in the start of this split, so I have a split character next to it, if we match schema for the exact check I won't be able to open it, due to line drawing being part of the schema, which we reject if you do exact match. So I'm in favor of keeping things as it is.

**Comment by chrisduerr** [comment]
This should be fairly easy to fix, since schemes can only accept the characters a-zA-Z. So we can easily accept `|https://x.y` while denying `ahttps://x.y`.

See: https://github.com/alacritty/urlocator/pull/5
